name: Loop Commit

on:
  schedule:
    - cron: '*/5 * * * *'   # every 1 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  loop-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add number 1 to file
        run: |
          echo "1" > file.txt
          git diff  # لرؤية التغيير إن وجد
          git add file.txt
          git commit -m "Add 1 to file" || echo "No changes to commit"
          git push || echo "Nothing to push"

      - name: Remove number 1 from file
        run: |
          echo "" > file.txt
          git diff
          git add file.txt
          git commit -m "Remove 1 from file" || echo "No changes to commit"
          git push || echo "Nothing to push"
